#include <iostream>
#include <fstream>

//Calculadora de Comandas por Liniker - GITHUB -> https://github.com/Canjica/

using namespace std;
int main(){
	int n1;
	float e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15, e16, e17, e18, e19, e20, e21, e22, e23, e24, e25, e26, e27, e28, e29, e30, total;
	char n [100];
	cout << "Digite nome do Garcom:" << endl;
	cin >> n;
	cout<< "Quantas contas?  " << endl;
	cin >> n1;
	cout << "========================" << endl;
	
	switch (n1){
		case 1:
			cin >> e1;
			total = e1;
			break;
		case 2:
			cin >> e1;
			cin >> e2;
			total = e1 + e2;
			break;
		case 3:
			cin >> e1;
			cin >> e2;
			cin >> e3;
			total = e1 + e2 + e3;
			break;
		case 4:
			cin >> e1;
			cin >> e2;
			cin >> e3;
			cin >> e4;
			
			total = e1 + e2 + e3 + e4;
			break;
		case 5:
			cin >> e1;
			cin >> e2;
			cin >> e3;
			cin >> e4;
			cin >> e5;
			
			total = e1 + e2 + e3 + e4 + e5;
			break;
		case 6:
			cin >> e1;
			cin >> e2;
			cin >> e3;
			cin >> e4;
			cin >> e5;
			cin >> e6;
			
			total = e1 + e2 + e3 + e4 + e5 + e6;
			break;
		case 7:
			cin >> e1;
			cin >> e2;
			cin >> e3;
			cin >> e4;
			cin >> e5;
			cin >> e6;
			cin >> e7;
		
			total = e1 + e2 + e3 + e4 + e5 + e6 + e7;
			break;
		case 8:
			cin >> e1;
			cin >> e2;
			cin >> e3;
			cin >> e4;
			cin >> e5;
			cin >> e6;
			cin >> e7;
			cin >> e8;
			
			total = e1 + e2 + e3 + e4 + e5 + e6 + e7 + e8;
			break;
		case 9:
			cin >> e1;
			cin >> e2;
			cin >> e3;
			cin >> e4;
			cin >> e5;
			cin >> e6;
			cin >> e7;
			cin >> e8;
			cin >> e9;
			
			total = e1 + e2 + e3 + e4 + e5 + e6 + e7 + e8 + e9;
			break;
		case 10:
			cin >> e1;
			cin >> e2;
			cin >> e3;
			cin >> e4;
			cin >> e5;
			cin >> e6;
			cin >> e7;
			cin >> e8;
			cin >> e9;
			cin >> e10;
			
			total = e1 + e2 + e3 + e4 + e5 + e6 + e7 + e8 + e9 + e10;
			break;
		case 11:
			cin >> e1;
			cin >> e2;
			cin >> e3;
			cin >> e4;
			cin >> e5;
			cin >> e6;
			cin >> e7;
			cin >> e8;
			cin >> e9;
			cin >> e10;
			cin >> e11;
			total = e1 + e2 + e3 + e4 + e5 + e6 + e7 + e8 + e9 + e10 + e11;
			break;
		case 12:
			cin >> e1;
			cin >> e2;
			cin >> e3;
			cin >> e4;
			cin >> e5;
			cin >> e6;
			cin >> e7;
			cin >> e8;
			cin >> e9;
			cin >> e10;
			cin >> e11;
			cin >> e12;
			total = e1 + e2 + e3 + e4 + e5 + e6 + e7 + e8 + e9 + e10 + e11 + e12;
			break;
		case 13:
			cin >> e1;
			cin >> e2;
			cin >> e3;
			cin >> e4;
			cin >> e5;
			cin >> e6;
			cin >> e7;
			cin >> e8;
			cin >> e9;
			cin >> e10;
			cin >> e11;
			cin >> e12;
			cin >> e13;
			total = e1 + e2 + e3 + e4 + e5 + e6 + e7 + e8 + e9 + e10 + e11 + e12 + e13;
			break;
		case 14:
			cin >> e1;
			cin >> e2;
			cin >> e3;
			cin >> e4;
			cin >> e5;
			cin >> e6;
			cin >> e7;
			cin >> e8;
			cin >> e9;
			cin >> e10;
			cin >> e11;
			cin >> e12;
			cin >> e13;
			cin >> e14;
			total = e1 + e2 + e3 + e4 + e5 + e6 + e7 + e8 + e9 + e10 + e11 + e12 + e13 + e14;
			break;
		case 15:
			cin >> e1;
			cin >> e2;
			cin >> e3;
			cin >> e4;
			cin >> e5;
			cin >> e6;
			cin >> e7;
			cin >> e8;
			cin >> e9;
			cin >> e10;
			cin >> e11;
			cin >> e12;
			cin >> e13;
			cin >> e14;
			cin >> e15;
			total = e1 + e2 + e3 + e4 + e5 + e6 + e7 + e8 + e9 + e10 + e11 + e12 + e13 + e14 + e15;
			break;
		case 16:
			cin >> e1;
			cin >> e2;
			cin >> e3;
			cin >> e4;
			cin >> e5;
			cin >> e6;
			cin >> e7;
			cin >> e8;
			cin >> e9;
			cin >> e10;
			cin >> e11;
			cin >> e12;
			cin >> e13;
			cin >> e14;
			cin >> e15;
			cin >> e16;
			total = e1 + e2 + e3 + e4 + e5 + e6 + e7 + e8 + e9 + e10 + e11 + e12 + e13 + e14 + e15 + e16;
			break;
		case 17:
			cin >> e1;
			cin >> e2;
			cin >> e3;
			cin >> e4;
			cin >> e5;
			cin >> e6;
			cin >> e7;
			cin >> e8;
			cin >> e9;
			cin >> e10;
			cin >> e11;
			cin >> e12;
			cin >> e13;
			cin >> e14;
			cin >> e15;
			cin >> e16;
			cin >> e17;
			total = e1 + e2 + e3 + e4 + e5 + e6 + e7 + e8 + e9 + e10 + e11 + e12 + e13 + e14 + e15 + e16 + e17;
			break;
		case 18:
			cin >> e1;
			cin >> e2;
			cin >> e3;
			cin >> e4;
			cin >> e5;
			cin >> e6;
			cin >> e7;
			cin >> e8;
			cin >> e9;
			cin >> e10;
			cin >> e11;
			cin >> e12;
			cin >> e13;
			cin >> e14;
			cin >> e15;
			cin >> e16;
			cin >> e17;
			cin >> e18;
			total = e1 + e2 + e3 + e4 + e5 + e6 + e7 + e8 + e9 + e10 + e11 + e12 + e13 + e14 + e15 + e16 + e17 + e18;
			break;
			case 19:
			cin >> e1;
			cin >> e2;
			cin >> e3;
			cin >> e4;
			cin >> e5;
			cin >> e6;
			cin >> e7;
			cin >> e8;
			cin >> e9;
			cin >> e10;
			cin >> e11;
			cin >> e12;
			cin >> e13;
			cin >> e14;
			cin >> e15;
			cin >> e16;
			cin >> e17;
			cin >> e18;
			cin >> e19;
			total = e1 + e2 + e3 + e4 + e5 + e6 + e7 + e8 + e9 + e10 + e11 + e12 + e13 + e14 + e15 + e16 + e17 + e18 + e19;
			break;
			case 20:
			cin >> e1;
			cin >> e2;
			cin >> e3;
			cin >> e4;
			cin >> e5;
			cin >> e6;
			cin >> e7;
			cin >> e8;
			cin >> e9;
			cin >> e10;
			cin >> e11;
			cin >> e12;
			cin >> e13;
			cin >> e14;
			cin >> e15;
			cin >> e16;
			cin >> e17;
			cin >> e18;
			cin >> e19;
			cin >> e20;
			total = e1 + e2 + e3 + e4 + e5 + e6 + e7 + e8 + e9 + e10 + e11 + e12 + e13 + e14 + e15 + e16 + e17 + e18 + e19 + e20;
			break;
			case 21:
			cin >> e1;
			cin >> e2;
			cin >> e3;
			cin >> e4;
			cin >> e5;
			cin >> e6;
			cin >> e7;
			cin >> e8;
			cin >> e9;
			cin >> e10;
			cin >> e11;
			cin >> e12;
			cin >> e13;
			cin >> e14;
			cin >> e15;
			cin >> e16;
			cin >> e17;
			cin >> e18;
			cin >> e19;
			cin >> e20;
			cin >> e21;
			total = e1 + e2 + e3 + e4 + e5 + e6 + e7 + e8 + e9 + e10 + e11 + e12 + e13 + e14 + e15 + e16 + e17 + e18 + e19 + e20 + e21;
			break;
			case 22:
			cin >> e1;
			cin >> e2;
			cin >> e3;
			cin >> e4;
			cin >> e5;
			cin >> e6;
			cin >> e7;
			cin >> e8;
			cin >> e9;
			cin >> e10;
			cin >> e11;
			cin >> e12;
			cin >> e13;
			cin >> e14;
			cin >> e15;
			cin >> e16;
			cin >> e17;
			cin >> e18;
			cin >> e19;
			cin >> e20;
			cin >> e21;
			cin >> e22;
			total = e1 + e2 + e3 + e4 + e5 + e6 + e7 + e8 + e9 + e10 + e11 + e12 + e13 + e14 + e15 + e16 + e17 + e18 + e19 + e20 + e21 + e22;
			break;
			case 23:
			cin >> e1;
			cin >> e2;
			cin >> e3;
			cin >> e4;
			cin >> e5;
			cin >> e6;
			cin >> e7;
			cin >> e8;
			cin >> e9;
			cin >> e10;
			cin >> e11;
			cin >> e12;
			cin >> e13;
			cin >> e14;
			cin >> e15;
			cin >> e16;
			cin >> e17;
			cin >> e18;
			cin >> e19;
			cin >> e20;
			cin >> e21;
			cin >> e22;
			cin >> e23;
			total = e1 + e2 + e3 + e4 + e5 + e6 + e7 + e8 + e9 + e10 + e11 + e12 + e13 + e14 + e15 + e16 + e17 + e18 + e19 + e20 + e21 + e22 + e23;
			break;
			case 24:
			cin >> e1;
			cin >> e2;
			cin >> e3;
			cin >> e4;
			cin >> e5;
			cin >> e6;
			cin >> e7;
			cin >> e8;
			cin >> e9;
			cin >> e10;
			cin >> e11;
			cin >> e12;
			cin >> e13;
			cin >> e14;
			cin >> e15;
			cin >> e16;
			cin >> e17;
			cin >> e18;
			cin >> e19;
			cin >> e20;
			cin >> e21;
			cin >> e22;
			cin >> e23;
			cin >> e24;
			total = e1 + e2 + e3 + e4 + e5 + e6 + e7 + e8 + e9 + e10 + e11 + e12 + e13 + e14 + e15 + e16 + e17 + e18 + e19 + e20 + e21 + e22 + e23 + e24;
			break;
			case 25:
			cin >> e1;
			cin >> e2;
			cin >> e3;
			cin >> e4;
			cin >> e5;
			cin >> e6;
			cin >> e7;
			cin >> e8;
			cin >> e9;
			cin >> e10;
			cin >> e11;
			cin >> e12;
			cin >> e13;
			cin >> e14;
			cin >> e15;
			cin >> e16;
			cin >> e17;
			cin >> e18;
			cin >> e19;
			cin >> e20;
			cin >> e21;
			cin >> e22;
			cin >> e23;
			cin >> e24;
			cin >> e25;
			total = e1 + e2 + e3 + e4 + e5 + e6 + e7 + e8 + e9 + e10 + e11 + e12 + e13 + e14 + e15 + e16 + e17 + e18 + e19 + e20 + e21 + e22 + e23 + e24 + e25;
			break;
			case 26:
			cin >> e1;
			cin >> e2;
			cin >> e3;
			cin >> e4;
			cin >> e5;
			cin >> e6;
			cin >> e7;
			cin >> e8;
			cin >> e9;
			cin >> e10;
			cin >> e11;
			cin >> e12;
			cin >> e13;
			cin >> e14;
			cin >> e15;
			cin >> e16;
			cin >> e17;
			cin >> e18;
			cin >> e19;
			cin >> e20;
			cin >> e21;
			cin >> e22;
			cin >> e23;
			cin >> e24;
			cin >> e25;
			cin >> e26;
			total = e1 + e2 + e3 + e4 + e5 + e6 + e7 + e8 + e9 + e10 + e11 + e12 + e13 + e14 + e15 + e16 + e17 + e18 + e19 + e20 + e21 + e22 + e23 + e24 + e25 + e26;
			break;
			case 27:
			cin >> e1;
			cin >> e2;
			cin >> e3;
			cin >> e4;
			cin >> e5;
			cin >> e6;
			cin >> e7;
			cin >> e8;
			cin >> e9;
			cin >> e10;
			cin >> e11;
			cin >> e12;
			cin >> e13;
			cin >> e14;
			cin >> e15;
			cin >> e16;
			cin >> e17;
			cin >> e18;
			cin >> e19;
			cin >> e20;
			cin >> e21;
			cin >> e22;
			cin >> e23;
			cin >> e24;
			cin >> e25;
			cin >> e26;
			cin >> e27;
			total = e1 + e2 + e3 + e4 + e5 + e6 + e7 + e8 + e9 + e10 + e11 + e12 + e13 + e14 + e15 + e16 + e17 + e18 + e19 + e20 + e21 + e22 + e23 + e24 + e25 + e26 + e27;
			break;
			case 28:
			cin >> e1;
			cin >> e2;
			cin >> e3;
			cin >> e4;
			cin >> e5;
			cin >> e6;
			cin >> e7;
			cin >> e8;
			cin >> e9;
			cin >> e10;
			cin >> e11;
			cin >> e12;
			cin >> e13;
			cin >> e14;
			cin >> e15;
			cin >> e16;
			cin >> e17;
			cin >> e18;
			cin >> e19;
			cin >> e20;
			cin >> e21;
			cin >> e22;
			cin >> e23;
			cin >> e24;
			cin >> e25;
			cin >> e26;
			cin >> e27;
			cin >> e28;
			total = e1 + e2 + e3 + e4 + e5 + e6 + e7 + e8 + e9 + e10 + e11 + e12 + e13 + e14 + e15 + e16 + e17 + e18 + e19 + e20 + e21 + e22 + e23 + e24 + e25 + e26 + e27 + e28;
			break;
			case 29:
			cin >> e1;
			cin >> e2;
			cin >> e3;
			cin >> e4;
			cin >> e5;
			cin >> e6;
			cin >> e7;
			cin >> e8;
			cin >> e9;
			cin >> e10;
			cin >> e11;
			cin >> e12;
			cin >> e13;
			cin >> e14;
			cin >> e15;
			cin >> e16;
			cin >> e17;
			cin >> e18;
			cin >> e19;
			cin >> e20;
			cin >> e21;
			cin >> e22;
			cin >> e23;
			cin >> e24;
			cin >> e25;
			cin >> e26;
			cin >> e27;
			cin >> e28;
			cin >> e29;
			total = e1 + e2 + e3 + e4 + e5 + e6 + e7 + e8 + e9 + e10 + e11 + e12 + e13 + e14 + e15 + e16 + e17 + e18 + e19 + e20 + e21 + e22 + e23 + e24 + e25 + e26 + e27 + e28 + e29;
			break;
		case 30:
			cin >> e1;
			cin >> e2;
			cin >> e3;
			cin >> e4;
			cin >> e5;
			cin >> e6;
			cin >> e7;
			cin >> e8;
			cin >> e9;
			cin >> e10;
			cin >> e11;
			cin >> e12;
			cin >> e13;
			cin >> e14;
			cin >> e15;
			cin >> e16;
			cin >> e17;
			cin >> e18;
			cin >> e19;
			cin >> e20;
			cin >> e21;
			cin >> e22;
			cin >> e23;
			cin >> e24;
			cin >> e25;
			cin >> e26;
			cin >> e27;
			cin >> e28;
			cin >> e29;
			cin >> e30;
			total = e1 + e2 + e3 + e4 + e5 + e6 + e7 + e8 + e9 + e10 + e11 + e12 + e13 + e14 + e15 + e16 + e17 + e18 + e19 + e20 + e21 + e22 + e23 + e24 + e25 + e26 + e27 + e28 + e29 + e30;
			break;
	default :
		cout << "ERROR" << endl;
	}
	cout << "Total = " << total << endl;
	
	ofstream file;
    file.open("impressao.txt");
    file<<"========== Garcom ==============  " << endl;
    file<<"            " << n << "           " << endl;
    file<<"================================  " << endl;
    switch (n1){
    	case 1:
    		file<< e1 << endl;
    		break;
    	case 2:
    		file<< e1 << endl;
    		file<< e2 << endl;
    		break;
    	case 3:
    		file<< e1 << endl;
    		file<< e2 << endl;
    		file<< e3 << endl;
    		break;
    	case 4:
    		file<< e1 << endl;
    		file<< e2 << endl;
    		file<< e3 << endl;
    		file<< e4 << endl;
    		break;
    	case 5:
    		file<< e1 << endl;
    		file<< e2 << endl;
    		file<< e3 << endl;
    		file<< e4 << endl;
    		file<< e5 << endl;
    		break;
    	case 6:
    		file<< e1 << endl;
    		file<< e2 << endl;
    		file<< e3 << endl;
    		file<< e4 << endl;
    		file<< e5 << endl;
    		file<< e6 << endl;
    		break;
    	case 7:
    		file<< e1 << endl;
    		file<< e2 << endl;
    		file<< e3 << endl;
    		file<< e4 << endl;
    		file<< e5 << endl;
    		file<< e6 << endl;
    		file<< e7 << endl;
    		break;
    	case 8:
    		file<< e1 << endl;
    		file<< e2 << endl;
    		file<< e3 << endl;
    		file<< e4 << endl;
    		file<< e5 << endl;
    		file<< e6 << endl;
    		file<< e7 << endl;
    		file<< e8 << endl;
    		break;
    	case 9:
    		file<< e1 << endl;
    		file<< e2 << endl;
    		file<< e3 << endl;
    		file<< e4 << endl;
    		file<< e5 << endl;
    		file<< e6 << endl;
    		file<< e7 << endl;
    		file<< e8 << endl;
    		file<< e9 << endl;
    		break;
    	case 10:
    		file<< e1 << endl;
    		file<< e2 << endl;
    		file<< e3 << endl;
    		file<< e4 << endl;
    		file<< e5 << endl;
    		file<< e6 << endl;
    		file<< e7 << endl;
    		file<< e8 << endl;
    		file<< e9 << endl;
    		file<< e10 << endl;
    		break;
    	case 11:
    		file<< e1 << endl;
    		file<< e2 << endl;
    		file<< e3 << endl;
    		file<< e4 << endl;
    		file<< e5 << endl;
    		file<< e6 << endl;
    		file<< e7 << endl;
    		file<< e8 << endl;
    		file<< e9 << endl;
    		file<< e10 << endl;
    		file<< e11 << endl;
    		break;
    	case 12:
    		file<< e1 << endl;
    		file<< e2 << endl;
    		file<< e3 << endl;
    		file<< e4 << endl;
    		file<< e5 << endl;
    		file<< e6 << endl;
    		file<< e7 << endl;
    		file<< e8 << endl;
    		file<< e9 << endl;
    		file<< e10 << endl;
    		file<< e11 << endl;
    		file<< e12 << endl;
    		break;
    	case 13:
    		file<< e1 << endl;
    		file<< e2 << endl;
    		file<< e3 << endl;
    		file<< e4 << endl;
    		file<< e5 << endl;
    		file<< e6 << endl;
    		file<< e7 << endl;
    		file<< e8 << endl;
    		file<< e9 << endl;
    		file<< e10 << endl;
    		file<< e11 << endl;
    		file<< e12 << endl;
    		file<< e13 << endl;
    		break;
    	case 14:
    		file<< e1 << endl;
    		file<< e2 << endl;
    		file<< e3 << endl;
    		file<< e4 << endl;
    		file<< e5 << endl;
    		file<< e6 << endl;
    		file<< e7 << endl;
    		file<< e8 << endl;
    		file<< e9 << endl;
    		file<< e10 << endl;
    		file<< e11 << endl;
    		file<< e12 << endl;
    		file<< e13 << endl;
    		file<< e14 << endl;
    		break;
    	case 15:
    		file<< e1 << endl;
    		file<< e2 << endl;
    		file<< e3 << endl;
    		file<< e4 << endl;
    		file<< e5 << endl;
    		file<< e6 << endl;
    		file<< e7 << endl;
    		file<< e8 << endl;
    		file<< e9 << endl;
    		file<< e10 << endl;
    		file<< e11 << endl;
    		file<< e12 << endl;
    		file<< e13 << endl;
    		file<< e14 << endl;
    		file<< e15 << endl;
    		break;
    	case 16:
    		file<< e1 << endl;
    		file<< e2 << endl;
    		file<< e3 << endl;
    		file<< e4 << endl;
    		file<< e5 << endl;
    		file<< e6 << endl;
    		file<< e7 << endl;
    		file<< e8 << endl;
    		file<< e9 << endl;
    		file<< e10 << endl;
    		file<< e11 << endl;
    		file<< e12 << endl;
    		file<< e13 << endl;
    		file<< e14 << endl;
    		file<< e15 << endl;
    		file<< e16 << endl;
    		break;
    	case 17:
    		file<< e1 << endl;
    		file<< e2 << endl;
    		file<< e3 << endl;
    		file<< e4 << endl;
    		file<< e5 << endl;
    		file<< e6 << endl;
    		file<< e7 << endl;
    		file<< e8 << endl;
    		file<< e9 << endl;
    		file<< e10 << endl;
    		file<< e11 << endl;
    		file<< e12 << endl;
    		file<< e13 << endl;
    		file<< e14 << endl;
    		file<< e15 << endl;
    		file<< e16 << endl;
    		file<< e17 << endl;
    		break;
    	case 18:
    		file<< e1 << endl;
    		file<< e2 << endl;
    		file<< e3 << endl;
    		file<< e4 << endl;
    		file<< e5 << endl;
    		file<< e6 << endl;
    		file<< e7 << endl;
    		file<< e8 << endl;
    		file<< e9 << endl;
    		file<< e10 << endl;
    		file<< e11 << endl;
    		file<< e12 << endl;
    		file<< e13 << endl;
    		file<< e14 << endl;
    		file<< e15 << endl;
    		file<< e16 << endl;
    		file<< e17 << endl;
    		file<< e18 << endl;
    		break;
    	case 19:
    		file<< e1 << endl;
    		file<< e2 << endl;
    		file<< e3 << endl;
    		file<< e4 << endl;
    		file<< e5 << endl;
    		file<< e6 << endl;
    		file<< e7 << endl;
    		file<< e8 << endl;
    		file<< e9 << endl;
    		file<< e10 << endl;
    		file<< e11 << endl;
    		file<< e12 << endl;
    		file<< e13 << endl;
    		file<< e14 << endl;
    		file<< e15 << endl;
    		file<< e16 << endl;
    		file<< e17 << endl;
    		file<< e18 << endl;
    		file<< e19 << endl;
    		break;
    	case 20:
    		file<< e1 << endl;
    		file<< e2 << endl;
    		file<< e3 << endl;
    		file<< e4 << endl;
    		file<< e5 << endl;
    		file<< e6 << endl;
    		file<< e7 << endl;
    		file<< e8 << endl;
    		file<< e9 << endl;
    		file<< e10 << endl;
    		file<< e11 << endl;
    		file<< e12 << endl;
    		file<< e13 << endl;
    		file<< e14 << endl;
    		file<< e15 << endl;
    		file<< e16 << endl;
    		file<< e17 << endl;
    		file<< e18 << endl;
    		file<< e19 << endl;
    		file<< e20 << endl;
    		break;
    	case 21:
    		file<< e1 << endl;
    		file<< e2 << endl;
    		file<< e3 << endl;
    		file<< e4 << endl;
    		file<< e5 << endl;
    		file<< e6 << endl;
    		file<< e7 << endl;
    		file<< e8 << endl;
    		file<< e9 << endl;
    		file<< e10 << endl;
    		file<< e11 << endl;
    		file<< e12 << endl;
    		file<< e13 << endl;
    		file<< e14 << endl;
    		file<< e15 << endl;
    		file<< e16 << endl;
    		file<< e17 << endl;
    		file<< e18 << endl;
    		file<< e19 << endl;
    		file<< e20 << endl;
    		file<< e21 << endl;
    		break;
    	case 22:
    		file<< e1 << endl;
    		file<< e2 << endl;
    		file<< e3 << endl;
    		file<< e4 << endl;
    		file<< e5 << endl;
    		file<< e6 << endl;
    		file<< e7 << endl;
    		file<< e8 << endl;
    		file<< e9 << endl;
    		file<< e10 << endl;
    		file<< e11 << endl;
    		file<< e12 << endl;
    		file<< e13 << endl;
    		file<< e14 << endl;
    		file<< e15 << endl;
    		file<< e16 << endl;
    		file<< e17 << endl;
    		file<< e18 << endl;
    		file<< e19 << endl;
    		file<< e20 << endl;
    		file<< e21 << endl;
    		file<< e22 << endl;
    		break;
    	case 23:
    		file<< e1 << endl;
    		file<< e2 << endl;
    		file<< e3 << endl;
    		file<< e4 << endl;
    		file<< e5 << endl;
    		file<< e6 << endl;
    		file<< e7 << endl;
    		file<< e8 << endl;
    		file<< e9 << endl;
    		file<< e10 << endl;
    		file<< e11 << endl;
    		file<< e12 << endl;
    		file<< e13 << endl;
    		file<< e14 << endl;
    		file<< e15 << endl;
    		file<< e16 << endl;
    		file<< e17 << endl;
    		file<< e18 << endl;
    		file<< e19 << endl;
    		file<< e20 << endl;
    		file<< e21 << endl;
    		file<< e22 << endl;
    		file<< e23 << endl;
    		break;
    	case 24:
    		file<< e1 << endl;
    		file<< e2 << endl;
    		file<< e3 << endl;
    		file<< e4 << endl;
    		file<< e5 << endl;
    		file<< e6 << endl;
    		file<< e7 << endl;
    		file<< e8 << endl;
    		file<< e9 << endl;
    		file<< e10 << endl;
    		file<< e11 << endl;
    		file<< e12 << endl;
    		file<< e13 << endl;
    		file<< e14 << endl;
    		file<< e15 << endl;
    		file<< e16 << endl;
    		file<< e17 << endl;
    		file<< e18 << endl;
    		file<< e19 << endl;
    		file<< e20 << endl;
    		file<< e21 << endl;
    		file<< e22 << endl;
    		file<< e23 << endl;
    		file<< e24 << endl;
    		break;
    	case 25:
    		file<< e1 << endl;
    		file<< e2 << endl;
    		file<< e3 << endl;
    		file<< e4 << endl;
    		file<< e5 << endl;
    		file<< e6 << endl;
    		file<< e7 << endl;
    		file<< e8 << endl;
    		file<< e9 << endl;
    		file<< e10 << endl;
    		file<< e11 << endl;
    		file<< e12 << endl;
    		file<< e13 << endl;
    		file<< e14 << endl;
    		file<< e15 << endl;
    		file<< e16 << endl;
    		file<< e17 << endl;
    		file<< e18 << endl;
    		file<< e19 << endl;
    		file<< e20 << endl;
    		file<< e21 << endl;
    		file<< e22 << endl;
    		file<< e23 << endl;
    		file<< e24 << endl;
    		file<< e25 << endl;
    		break;
    	case 26:
    		file<< e1 << endl;
    		file<< e2 << endl;
    		file<< e3 << endl;
    		file<< e4 << endl;
    		file<< e5 << endl;
    		file<< e6 << endl;
    		file<< e7 << endl;
    		file<< e8 << endl;
    		file<< e9 << endl;
    		file<< e10 << endl;
    		file<< e11 << endl;
    		file<< e12 << endl;
    		file<< e13 << endl;
    		file<< e14 << endl;
    		file<< e15 << endl;
    		file<< e16 << endl;
    		file<< e17 << endl;
    		file<< e18 << endl;
    		file<< e19 << endl;
    		file<< e20 << endl;
    		file<< e21 << endl;
    		file<< e22 << endl;
    		file<< e23 << endl;
    		file<< e24 << endl;
    		file<< e25 << endl;
    		file<< e26 << endl;
    		break;
    	case 27:
    		file<< e1 << endl;
    		file<< e2 << endl;
    		file<< e3 << endl;
    		file<< e4 << endl;
    		file<< e5 << endl;
    		file<< e6 << endl;
    		file<< e7 << endl;
    		file<< e8 << endl;
    		file<< e9 << endl;
    		file<< e10 << endl;
    		file<< e11 << endl;
    		file<< e12 << endl;
    		file<< e13 << endl;
    		file<< e14 << endl;
    		file<< e15 << endl;
    		file<< e16 << endl;
    		file<< e17 << endl;
    		file<< e18 << endl;
    		file<< e19 << endl;
    		file<< e20 << endl;
    		file<< e21 << endl;
    		file<< e22 << endl;
    		file<< e23 << endl;
    		file<< e24 << endl;
    		file<< e25 << endl;
    		file<< e26 << endl;
    		file<< e27 << endl;
    		break;
    	case 28:
    		file<< e1 << endl;
    		file<< e2 << endl;
    		file<< e3 << endl;
    		file<< e4 << endl;
    		file<< e5 << endl;
    		file<< e6 << endl;
    		file<< e7 << endl;
    		file<< e8 << endl;
    		file<< e9 << endl;
    		file<< e10 << endl;
    		file<< e11 << endl;
    		file<< e12 << endl;
    		file<< e13 << endl;
    		file<< e14 << endl;
    		file<< e15 << endl;
    		file<< e16 << endl;
    		file<< e17 << endl;
    		file<< e18 << endl;
    		file<< e19 << endl;
    		file<< e20 << endl;
    		file<< e21 << endl;
    		file<< e22 << endl;
    		file<< e23 << endl;
    		file<< e24 << endl;
    		file<< e25 << endl;
    		file<< e26 << endl;
    		file<< e27 << endl;
    		file<< e28 << endl;
    		break;
    	case 29:
    		file<< e1 << endl;
    		file<< e2 << endl;
    		file<< e3 << endl;
    		file<< e4 << endl;
    		file<< e5 << endl;
    		file<< e6 << endl;
    		file<< e7 << endl;
    		file<< e8 << endl;
    		file<< e9 << endl;
    		file<< e10 << endl;
    		file<< e11 << endl;
    		file<< e12 << endl;
    		file<< e13 << endl;
    		file<< e14 << endl;
    		file<< e15 << endl;
    		file<< e16 << endl;
    		file<< e17 << endl;
    		file<< e18 << endl;
    		file<< e19 << endl;
    		file<< e20 << endl;
    		file<< e21 << endl;
    		file<< e22 << endl;
    		file<< e23 << endl;
    		file<< e24 << endl;
    		file<< e25 << endl;
    		file<< e26 << endl;
    		file<< e27 << endl;
    		file<< e28 << endl;
    		file<< e29 << endl;
    		break;
    	case 30:
    		file<< e1 << endl;
    		file<< e2 << endl;
    		file<< e3 << endl;
    		file<< e4 << endl;
    		file<< e5 << endl;
    		file<< e6 << endl;
    		file<< e7 << endl;
    		file<< e8 << endl;
    		file<< e9 << endl;
    		file<< e10 << endl;
    		file<< e11 << endl;
    		file<< e12 << endl;
    		file<< e13 << endl;
    		file<< e14 << endl;
    		file<< e15 << endl;
    		file<< e16 << endl;
    		file<< e17 << endl;
    		file<< e18 << endl;
    		file<< e19 << endl;
    		file<< e20 << endl;
    		file<< e21 << endl;
    		file<< e22 << endl;
    		file<< e23 << endl;
    		file<< e24 << endl;
    		file<< e25 << endl;
    		file<< e26 << endl;
    		file<< e27 << endl;
    		file<< e28 << endl;
    		file<< e29 << endl;
    		file<< e30 << endl;
    		break;
    	default:
    		cout<<"ERRO" << endl;
	}
    file<<"******************************" << endl;
    file<<"Total:     " << total << endl;
    file<<"******************************" << endl;
    file.close();
    system("notepad /p impressao.txt");
	system("pause");
}
